### ISSUE TITLE
Jar File not found in adding

### ISSUE THREAD

**Issue by Salve87** [marvkis/org.openhab.binding.bosesoundtouch-dist#1]
Hey Guys,
maybe you can help me.
I tried adding the .jar File zu the addons. Openhab2 PaperUI just doesn't show the Binding.
I tried same with the 2.0.0 version and the Binding shows up.
Am I doing something wrong?

Cheers

**Comment by marvkis** [comment]
Hi,
Which OH version do you have? Is it the 2.2 release or the 2.3 devel?
On the latest 2.3 devel version's i have seen issues that required dependencies are not resolved properly (the jetty websocket client libs and other jetty packages). You'll see some stacktraces complaining about those missing libs...

messages look like:
```
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.bosesoundtouch [236]
  Unresolved requirement: Import-Package: org.eclipse.jetty.websocket.client
```

on my devel setup a
```
feature:install openhab-httpclient
```
resolved the issue - now all dependencies are available and the plugin works again...

If you have any logs related to the problem you could attach it to this ticket.

Cheers

**Comment by Salve87** [comment]
Hey, i‘m using 2.3.0 Build 1231.
I am very new to OH. I didn‘t get any response from OH. How can i check that?

Thanks dir the great work 

Daniel

**Comment by marvkis** [comment]
Hi Daniel,

usually there is a log file in `userdata/logs/openhab.log` - but it might vary depending on your installation (os used / prepackaged packages / manually installed / ...)
Just look for the openhab.log file.

For OH 2.3 i've uploaded a new .jar file yesterday - please also have a look at #2 

And thank you for the compliments ;)

Cheers,
    Chris

**Comment by Salve87** [comment]
Ok i checked my logfile.
I found following note:

2018-04-05 15:56:41.317 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/volume1/homes/openhab/addons/org.openhab.binding.bosesoundtouch-2.3.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.bosesoundtouch [259]
  Unresolved requirement: Import-Package: org.eclipse.jetty.websocket.client

	at org.eclipse.osgi.container.Module.start(Module.java:444) [?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) [?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [9:org.apache.felix.fileinstall:3.6.4]


Can you help me? Whats is going wrong? Thanks alot

**Comment by marvkis** [comment]
Hi Daniel,

The message
>`Unresolved requirement: Import-Package: org.eclipse.jetty.websocket.client `
indicates exactly the dependency issue. You have to install the `openhab-httpclient` feature which installs all the dependencies the bose plugin needs.
Just type
```
feature:install openhab-httpclient
```
on the OH console to install the feature - then the Bose plugin will start working as excpected.

Cheers,
     Chris

**Comment by Salve87** [comment]
Hello Chris,
Thanks for the reply. 
I will do that as soon as i am at home.
I have the http Binding installed. Isn‘t that enough?

Thanks for the help.
Best regards Daniel
